# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"

  config.vm.network "private_network", ip: "192.168.56.50"

  config.vm.synced_folder "orders/", "/home/vagrant/orders"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
    config.vm.provision "shell", path: "bootstrap.sh"
  end

end
